cbv/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("todo_class/", views.TodoListView.as_view(), name="todo_class_list"),
    path("todo_class/<int:id>/update/", views.UpdateTodoView.as_view(), name="update"),
    path("todo_class/<int:id>/delete/", views.DeleteTodoView.as_view(), name="delete"),
    path("/create_todo/", views.CreateTodoView.as_view(), name="create_todo"),
]

main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from main.settings import DEBUG
from main_page import views


urlpatterns = [
    path("admin/", admin.site.urls),
    path("first_lesson_django/", views.first_lesson_django, name="first_lesson_django"),
    path("image_link/", views.picture_view, name="picture_view"),
    path("", include("main_page.urls")),
    path("", include("hashtags.urls")),
    path("", include("todo.urls")),
    path("", include("cbv.urls")),
    path("", include("parsing_rezka.urls")),
    path("", include("users.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


if settings.DEBUG:
    urlpatterns += [path("__debug__/", include("debug_toolbar.urls"))]

users/urls.py
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    path("register/", views.RegistrationView.as_view(), name="register"),
    path("login/", views.AuthLoginView.as_view(), name="login"),
    path("logout/", views.AuthLogoutView.as_view(), name="logout"),
    path("user_list/", views.UserListView.as_view(), name="user_list"),
]

main_page/models.py
from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models


class Films(models.Model):
    GENRE_CHOICE = (("Ужасы", "Ужасы"), ("Комедия", "Комедия"), ("Боевик", "Боевик"))
    image = models.ImageField(upload_to="film/", verbose_name="загрузите картинку")
    title = models.CharField(max_length=100, verbose_name="Укажите описание фильма")
    description = models.TextField(
        verbose_name="Укажите описание к фильму", default="Lorem Ipsum", null=True
    )
    price = models.FloatField(verbose_name="Укажите цену")
    start_film = models.DateField(verbose_name="укажите дату выхода")
    genre = models.CharField(
        max_length=100,
        choices=GENRE_CHOICE,
        default="Комедия",
        verbose_name="Укажите жанр",
    )
    time_end = models.TimeField(verbose_name="Укажите время продолжительности фильма")
    director = models.CharField(max_length=30, verbose_name="Укажите режиссёра")
    trailer = models.URLField(verbose_name="Укажите ссылку трейлера с youtube")
    created_at = models.DateTimeField(auto_now_add=True, null=True)

    def average_rating(self):
        reviews = self.review_films.all()
        if reviews:
            return sum(review.mark for review in reviews) / reviews.count()
        return None

    class Meta:
        verbose_name = "фильм"
        verbose_name_plural = "фильмы"

    def __str__(self):
        return f"{self.title}-{self.price}$"


class ReviewFilm(models.Model):
    review_films = models.ForeignKey(
        Films, on_delete=models.CASCADE, related_name="review_films"
    )
    created_at = models.DateField(auto_now_add=True)
    description = models.TextField(verbose_name="Оставьте отзыв о фильме")
    mark = models.PositiveIntegerField(
        verbose_name="Укажите оценку от 1 до 5",
        validators=[MinValueValidator(1), MaxValueValidator(5)],
    )

    def __str__(self):
        return f"{self.review_films}-{self.created_at}"

    class Meta:
        verbose_name = "комментарий"
        verbose_name_plural = "комментарии"

parsing_rezka/models.py
from django.db import models


class Rezka(models.Model):
    title = models.CharField(max_length=900)
    image = models.ImageField(null=True)

    def __str__(self):
        return self.title

templates/all_products_list_view.html
{% include 'header.html' %}

    <div class="container my-5">
        <div class="d-flex justify-content-around mb-4">
            <a href="{% url 'foods_products_tags' %}" class="btn btn-primary">#Еда</a>
            <a href="{% url 'drink_products_tags' %}" class="btn btn-secondary">#Напитки</a>
        </div>

        {% for i in products_list %}
        <div class="card" style="width: 18rem; margin: 0 auto;">
            <img src="https://marketing-course.ru/wp-content/uploads/2015/03/hashtag.jpg" class="card-img-top" alt="Изображение">
            <div class="card-body">
                <h5 class="card-title">{{ i.title }}</h5>
                <p class="card-text">{{ i.price }}</p>
            </div>
        </div>
        {% endfor %}


    </div>


{% include 'footer.html' %}

templates/drink.html
{% include 'header.html' %}

        {% for i in drink %}
        <div class="card" style="width: 18rem; margin: 0 auto;">
            <img src="https://marketing-course.ru/wp-content/uploads/2015/03/hashtag.jpg" class="card-img-top" alt="Изображение">
            <div class="card-body">
                <h5 class="card-title">{{ i.title }}</h5>
                <p class="card-text">{{ i.price }}</p>
            </div>
        </div>
        {% endfor %}




{% include 'footer.html' %}

templates/foods.html
{% include 'header.html' %}

        {% for i in foods %}
        <div class="card" style="width: 18rem; margin: 0 auto;">
            <img src="https://marketing-course.ru/wp-content/uploads/2015/03/hashtag.jpg" class="card-img-top" alt="Изображение">
            <div class="card-body">
                <h5 class="card-title">{{ i.title }}</h5>
                <p class="card-text">{{ i.price }}</p>
            </div>
        </div>
        {% endfor %}




{% include 'footer.html' %}

templates/footer.html
<footer>
    © 2024 Ваш Сайт:
    <a class="text-reset fw-bold" href="#" style="color: yellow;">ВашСайт.com</a>
</footer>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
        crossorigin="anonymous"></script>
</body>
</html>

templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Geek Movie</title>
    <link rel="stylesheet" href="{% static 'css/show.css' %}">
    <link rel="stylesheet" href="{% static 'css/show_detail.css' %}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="shortcut icon"
          href="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS9RaqWhNrT68sVwQFo4ZAs1VRsUZImppmaqg&s">
</head>
<body>

<!--Навигационная панель-->
<nav class="navbar navbar-expand-lg bg-body-tertiary fixed-top"
     style="background: linear-gradient(to right, #1a1919, #100f0f);">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="https://lh5.googleusercontent.com/yzWtzlXIlHfLjcFkr0S7UgmoX9HFoJ6VRszWZyEt-G85Gl5ID_XxoLX6Ji6E223S-EU2UUt2Y89uOwkm0tr8KkLQbM4Su17ln5HVBLaLHfxFIqm4DDpwmzPhfeAg1mja2Xdz7JkCvJqbpoEOT0CX8Cg"
                 alt="Logo" style="width: 40px; height: 40px;">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Переключатель навигации">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'films_list' %}" style="color: yellow;">Главная</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'all_products_tags' %}" style="color: yellow;">Хэш теги</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false" style="color: yellow;">
                        TODO definition
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'create_todo' %}">Добавить</a></li>
                        <li><a class="dropdown-item" href="{% url 'todoList' %}">Список задач</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false" style="color: yellow;">
                        TODO CLASSES
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'create_todo' %}">Добавить</a></li>
                        <li><a class="dropdown-item" href="{% url 'todo_class_list' %}">Список задач</a></li>
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                    </ul>
                </li>


                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'users:register' %}" style="color: yellow;">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link enable" href="{% url 'rezka_list' %}" style="color: yellow;">Другие фильмы</a>
                </li>
            </ul>
            <form action="{% url 'search' %}" method="GET" class="d-flex" role="search">
                <input class="form-control me-2" type="text" type="search" name="q" placeholder="Поиск"
                       aria-label="Поиск">
                <button class="btn btn-outline-success" type="submit" style="color: yellow; border-color: yellow;">
                    Поиск
                </button>
            </form>
        </div>
    </div>
</nav>

templates/show.html
<!--Подключение к header.html-->
{% include 'header.html' %}
<!-- Контент с карточками -->
<div class="container mt-4 content">
    <div class="row justify-content-center">
        {% for i in film_list %}
        {% load cache %}
        {% cache 600 film_list %}
        <!-- Пример для еще одной карточки -->
        <div class="col-md-4 mb-4">
            <div class="card" style="width: 100%;">
                <img src="{{ i.image.url }}" class="card-img-top" alt="вставьте логику картинки">
                <div class="card-body">
                    <h5 class="card-title">{{ i.title }}</h5>
                    <p class="card-text">{{ i.start_film }}</p>
                    <p class="card-text">Рейтинг: {{ i.average_rating|default:"нет рейтинга" }}</p>
                    <a href="/film_detail/{{ i.id }}/" class="btn btn-primary">Подробнее</a>
                </div>
            </div>
        </div>
        {% endcache %}
        {% endfor %}
    </div>
</div>
<!--Футер-->
{% include 'footer.html' %}

templates/show_detail.html
{% include 'header.html' %}
<!-- Контент с информацией о фильме -->
<div class="container mt-4">
    <div class="movie-card">
        <div class="card">
            <img src="{{ film_id.image.url }}" class="card-img-top" alt="Фильм">
            <div class="card-body">
                <h5 class="card-title">{{ film_id.title }}</h5>
                <p class="card-text">{{ film_id.description }}</p>
                <p><strong>Цена билета:</strong> ${{ film_id.price }}</p>
                <p><strong>Дата выхода:</strong> {{ film_id.start_film}}</p>
                <p><strong>Жанр:</strong> {{ film_id.genre}}</p>
                <p><strong>Время:</strong> {{ film_id.time_end }} минут</p>
                <p><strong>Режиссер:</strong> {{ film_id.director }}</p>
                <iframe width="100%" height="315" src="{{ film_id.trailer }}" frameborder="0" allowfullscreen></iframe>
            </div>
        </div>
    </div>

    <!-- Блок для комментариев -->
    <div class="comment-section">
        <h5>Комментарии</h5>
        <p>Общий рейтинг фильма - {{ film_id.average_rating|default:"нет рейтинга" }}</p>
<!--        {% if film_id.review_films.exists %}-->
<!--        <div class="comment">-->
<!--            <p> {{ film_id.review_films.first.created_at }}: {{ film_id.review_films.first.description }} <strong>Оценка:</strong> {{ film_id.review_films.first.mark }}</p>-->
<!--        </div>-->
<!--        {% endif %}-->


        {% for i in film_id.review_films.all %}
        <div class="comment">
            <p> {{ i.created_at }}: {{ i.description }} <strong>Оценка:</strong> {{ i.mark }}</p>
        </div>
        {% endfor %}
    </div>
</div>

<!-- Футер -->
{% include 'footer.html' %}